Locales['br'] = {
  -- Cloakroom
  ['cloakroom'] = 'vestiário',
  ['citizen_wear'] = 'Equipamento civil',
  ['police_wear'] = 'equipamento policial',
  ['gilet_wear'] = 'jaqueta reflexiva laranja',
  ['bullet_wear'] = 'colete a prova de balas',
  ['no_outfit'] = 'não há uniforme que sirva em você!',
  ['open_cloackroom'] = 'pressione [E] para trocar de roupa.',
  -- Armory
  ['remove_object'] = 'retirar objeto',
  ['deposit_object'] = 'Depositar Objeto',
  ['get_weapon'] = 'retirar arma do arsenal',
  ['put_weapon'] = 'armazenar arma no arsenal',
  ['buy_weapons'] = 'comprar armas',
  ['armory'] = 'arsenal',
  ['open_armory'] = 'pressione [E] para acessar o Arsenal.',
  ['armory_owned'] = 'comprado',
  ['armory_free'] = 'gratis',
  ['armory_item'] = '$%s',
  ['armory_weapontitle'] = 'arsenal - Compre arma',
  ['armory_componenttitle'] = 'arsenal - acessórios de armas',
  ['armory_bought'] = 'você comprou um %s para $%s',
  ['armory_money'] = 'você não pode pagar por essa arma',
  ['armory_hascomponent'] = 'você tem esse acessório equipado!',
  ['get_weapon_menu'] = 'arsenal - Retirar Arma',
  ['put_weapon_menu'] = 'arsenal - Armazenar Arma',
  ['confirm'] = 'Confirmar',
  -- Vehicles
  ['vehicle_menu'] = 'veículo',
  ['vehicle_blocked'] = 'todos os pontos de spawn disponíveis estão atualmente bloqueados!',
  ['garage_prompt'] = 'pressione [E] para acessar as Ações do Veículo.',
  ['garage_title'] = 'Ações do veículo',
  ['garage_stored'] = 'armazenado',
  ['garage_notstored'] = 'não esta na garagem',
  ['garage_storing'] = 'estamos tentando remover o veículo, certifique-se de que não haja jogadores por perto.',
  ['garage_has_stored'] = 'o veículo foi guardado na sua garagem',
  ['garage_has_notstored'] = 'nenhum veículo de propriedade próximo foi encontrado',
  ['garage_notavailable'] = 'seu veículo não está guardado na garagem.',
  ['garage_blocked'] = 'não há pontos de spawn disponíveis!',
  ['garage_empty'] = 'você não tem veículos em sua garagem.',
  ['garage_released'] = 'seu veículo foi liberado da garagem.',
  ['garage_store_nearby'] = 'não há veículos próximos.',
  ['garage_storeditem'] = 'abrir garagem',
  ['garage_storeitem'] = 'guardar veículo na garagem',
  ['garage_buyitem'] = 'loja de veículos',
  ['garage_notauthorized'] = 'você não está autorizado a comprar este tipo de veículos.',
  ['helicopter_prompt'] = 'pressione [E] para acessar as ações do helicóptero.',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Loja de veículos',
  ['vehicleshop_confirm'] = 'você quer comprar este veículo?',
  ['vehicleshop_bought'] = 'você comprou %s por ~r~$%s',
  ['vehicleshop_money'] = 'você não pode pagar esse veículo',
  ['vehicleshop_awaiting_model'] = 'o veículo está atualmente baixando e carregando, aguarde',
  ['confirm_no'] = 'não',
  ['confirm_yes'] = 'sim',
  ['view'] = 'Ver',
  ['buy_car'] = 'comprar',
  ['stop_view'] = 'parar de ver',
  -- Service
  ['service_max'] = 'você não pode entrar em serviço, máximo de oficiais em serviço: %s/%s',
  ['service_not'] = 'você não entrou em serviço! Você terá que se trocar primeiro.',
  ['service_anonunce'] = 'Serviço de informação',
  ['service_in'] = 'você entrou em serviço, seja bem-vindo!',
  ['service_in_announce'] = 'o operador %s entrou em serviço!',
  ['service_out'] = 'você saiu do serviço.',
  ['service_out_announce'] = 'o operador %s saiu do serviço.',
  -- Action Menu
  ['menu_title'] = 'Policia',
  ['citizen_interaction'] = 'Interação cidadão',
  ['vehicle_interaction'] = 'Interação do veículo',
  ['object_spawner'] = 'gerador de objeto',

  ['id_card'] = 'Carteira de identidade',
  ['search'] = 'procurar',
  ['handcuff'] = 'algemar / desalgemar',
  ['drag'] = 'escoltar',
  ['put_in_vehicle'] = 'colocar no veículo',
  ['out_the_vehicle'] = 'arrastar para fora do veículo',
  ['fine'] = 'multar',
  ['unpaid_bills'] = 'gerenciar contas não pagas',
  ['license_check'] = 'gerenciar licença',
  ['license_revoke'] = 'revogar licença',
  ['license_revoked'] = 'seu %s foi revogado!',
  ['licence_you_revoked'] = 'você revogou um %s que pertencia a %s',
  ['no_players_nearby'] = 'não há jogador(es) por perto!',
  ['being_searched'] = 'você está sendo revistado pela polícia',
  -- Vehicle interaction
  ['vehicle_info'] = 'Informações do veículo',
  ['pick_lock'] = 'Veículo lockpick',
  ['vehicle_unlocked'] = 'veículo desbloqueado',
  ['no_vehicles_nearby'] = 'não há veículos por perto',
  ['impound'] = 'apreender veículo',
  ['impound_prompt'] = 'pressione [E] para cancelar a apreensão',
  ['impound_canceled'] = 'você cancelou a apreensão',
  ['impound_canceled_moved'] = 'a apreensão foi cancelada porque o veículo se deslocou',
  ['impound_successful'] = 'você apreendeu o veículo',
  ['search_database'] = 'informações do veículo',
  ['search_database_title'] = 'informações do veículo - pesquise com número de registro',
  ['search_database_error_invalid'] = 'esse ~r~não é um número de registro válido',
  ['search_plate'] = 'Entrar na placa',
  ['lookup_plate'] = 'Placa de pesquisa',
  -- Traffic interaction
  ['traffic_interaction'] = 'interação Tráfego',
  ['cone'] = 'cone',
  ['barrier'] = 'barreira',
  ['spikestrips'] = 'Tapete de pregos',
  ['box'] = 'caixa',
  ['cash'] = 'caixa de dinheiro',
  -- ID Card Menu
  ['name'] = 'nome: %s',
  ['job'] = 'trabalho: %s',
  ['sex'] = 'sexo: %s',
  ['dob'] = 'aniversario: %s',
  ['height'] = 'altura: %s',
  ['bac'] = 'BAC: %s',
  ['unknown'] = 'unknown',
  ['male'] = 'homem',
  ['female'] = 'mulher',
  -- Body Search Menu
  ['guns_label'] = '--- armas ---',
  ['inventory_label'] = '--- Inventario ---',
  ['license_label'] = ' --- Licenças ---',
  ['confiscate'] = 'confiscar %s',
  ['confiscate_weapon'] = 'confiscar %s com %s muniçoes',
  ['confiscate_inv'] = 'confiscar %sx %s',
  ['confiscate_dirty'] = 'confiscar dinheiro sujo: <span style="color:red;">$%s</span>',
  ['you_confiscated'] = 'voce confiscou %sx %s de %s',
  ['got_confiscated'] = '%sx %s foram confiscados por %s',
  ['you_confiscated_account'] = 'você confiscou $%s (%s) de %s',
  ['got_confiscated_account'] = '$%s (%s) foi confiscado por %s',
  ['you_confiscated_weapon'] = 'você confiscou %s de %s com ~o~%s muniçoes',
  ['got_confiscated_weapon'] = 'seu %s com ~o~%s muniçoes foi confiscado por %s',
  ['traffic_offense'] = 'infração de trânsito',
  ['minor_offense'] = 'Ofensa menor',
  ['average_offense'] = 'Ofensa média',
  ['major_offense'] = 'ofensa grave',
  ['fine_total'] = 'multar: %s',
  -- Vehicle Info Menu
  ['plate'] = 'placa: %s',
  ['owner_unknown'] = 'dono: Unknown',
  ['owner'] = 'dono: %s',
  -- Boss Menu
  ['open_bossmenu'] = 'pressione [E] para abrir o menu',
  ['quantity_invalid'] = 'quantidade inválida',
  ['have_withdrawn'] = 'você retirou %sx %s',
  ['have_deposited'] = 'você depositou %sx %s',
  ['quantity'] = 'quantidade',
  ['quantity_placeholder'] = 'Quantidade à sacar..',
  ['inventory'] = 'inventario',
  ['police_stock'] = 'Estoque da polícia',
  -- Misc
  ['remove_prop'] = 'pressione [E] para excluir o objeto',
  ['map_blip'] = 'Delegacia de polícia',
  ['unrestrained_timer'] = 'você sente suas algemas perdendo lentamente o controle e desaparecendo.',
  -- Notifications
  ['alert_police'] = 'alerta policial',
  ['phone_police'] = 'policia',
  -- Keybind
  ['interaction'] = 'Interagir',
  ['quick_actions'] = 'Ações rápidas',
  -- Other
  ['society_police'] = 'Policia',
  ['s_m_y_sheriff_01'] = 'Xerife Ped', 
  ['s_m_y_cop_01'] = 'Polícial Ped.',
  ['s_m_y_swat_01'] = 'SWAT Ped',
}
