Locales ['br'] = {
  ['valid_purchase'] = 'validar esta compra?',
  ['yes'] = 'Sim(<span style="color: green;">$%s</span>)',
  ['no'] = 'não',
  ['helmet'] = 'capacete / chapéu',
  ['glasses'] = 'Oculos',
  ['mask'] = 'Mascara',
  ['ears'] = 'acessórios para orelhas',
  ['shop'] = '%s shop',
  ['set_unset'] = 'colocar / tirar',
  ['not_enough_money'] = 'você não tem dinheiro suficiente',
  ['press_access'] = 'pressione [E] para acessar o menu',
  ['accessories_blip'] = 'acessórios',
  ['no_ears'] = 'você não tem acessórios para orelhas',
  ['no_glasses'] = 'você não tem óculos',
  ['no_helmet'] = 'você não tem capacete',
  ['no_mask'] = 'você não tem máscara',
  ['you_paid'] = 'você pagou $%s',
  ['keymap'] = 'Abra o menu de acessórios',
}
