Locales['br'] = {
  -- Cloakroom
  ['cloakroom'] = 'Vestiário',
  ['ems_clothes_civil'] = 'Roupas Civis',
  ['ems_clothes_ems'] = 'Roupas EMS',
  -- Vehicles
  ['ambulance'] = 'Ambulancia',
  ['helicopter_prompt'] = 'Pressione [E] para acessar as ações do helicóptero.',
  ['garage_prompt'] = 'Pressione [E] para acessar as Ações do Veículo.',
  ['garage_title'] = 'Ações do Veículo',
  ['garage_stored'] = 'Armazenado',
  ['garage_notstored'] = 'Não esta na garagem',
  ['garage_storing'] = 'Estamos tentando remover o veículo, certifique-se de que não haja jogadores por perto.',
  ['garage_has_stored'] = 'O veículo foi guardado na sua garagem',
  ['garage_has_notstored'] = 'Nenhum veículo de propriedade próximo foi encontrado',
  ['garage_notavailable'] = 'Seu veículo não está guardado na garagem.',
  ['garage_blocked'] = 'Não há pontos de spawn disponíveis!',
  ['garage_empty'] = 'Você não tem veículos em sua garagem.',
  ['garage_released'] = 'Seu veículo foi liberado da garagem.',
  ['garage_store_nearby'] = 'Não há veículos próximos.',
  ['garage_storeditem'] = 'Garagem aberta',
  ['garage_storeitem'] = 'Guarde o veículo na garagem',
  ['garage_buyitem'] = 'Loja de veículos',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Loja de veículos',
  ['vehicleshop_confirm'] = 'Você quer comprar este veículo?',
  ['vehicleshop_bought'] = 'Você comprou %s por $%s',
  ['vehicleshop_money'] = 'Você não pode pagar esse veículo',
  ['vehicleshop_awaiting_model'] = 'O veículo está atualmente BAIXANDO E CARREGANDO, aguarde',
  ['confirm_no'] = 'Não',
  ['confirm_yes'] = 'Sim',
  -- Action Menu
  ['revive_inprogress'] = 'Uma ressuscitação está em andamento!',
  ['revive_complete'] = 'Você reviveu %s',
  ['revive_complete_award'] = 'Você reviveu %s e ganhou $%s!',
  ['revive_fail_offline'] = 'Esse jogador não está mais online',
  ['heal_inprogress'] = 'Você está curando!',
  ['heal_complete'] = 'Você curou %s',
  ['no_players'] = 'Nenhum jogador por perto',
  ['player_not_unconscious'] = 'Esse jogador não está inconsciente!',
  ['player_not_conscious'] = 'Esse jogador não está consciente!',
  -- Boss Menu
  ['boss_actions'] = 'Ações do chefe',
  -- Misc
  ['invalid_amount'] = 'Quantia inválida',
  ['actions_prompt'] = 'Pressione [E] para acessar as Ações de Ambulância.',
  ['deposit_amount'] = 'Quantidade do depósito',
  ['money_withdraw'] = 'Valor retirado',
  ['fast_travel'] = 'pressione [E] para viagem rápida.',
  ['open_pharmacy'] = 'Pressione [E] para abrir a farmácia.',
  ['pharmacy_menu_title'] = 'Farmacia',
  ['pharmacy_take'] = 'Pegar <span style="color:blue;">%s</span>',
  ['medikit'] = 'Kit médico',
  ['bandage'] = 'Bandagem',
  ['max_item'] = 'Você já está carregando o suficiente.',
  ['unconscious_found'] = '[DISPATCH]: Uma pessoa inconsciente foi denunciada',
  -- F6 Menu
  ['ems_menu'] = 'EMS Menu',
  ['ems_menu_title'] = 'Ambulância - Menu EMS',
  ['ems_menu_revive'] = 'Reviver Jogador',
  ['ems_menu_putincar'] = 'Colocar no veículo',
  ['ems_menu_small'] = 'Curar pequenas feridas',
  ['ems_menu_big'] = 'Trate ferimentos graves',
  ['ems_menu_search'] = 'Paciente não encontrado',
  -- Phone
  ['alert_ambulance'] = 'Ambulância de Alerta',
  -- Death
  ['respawn_available_in'] = 'Respawn disponível em %s minutos %s segundos',
  ['respawn_bleedout_in'] = 'Você sangrará em %s minutos %s segundos\n',
  ['respawn_bleedout_prompt'] = 'Segure [E] para reaparecer',
  ['respawn_bleedout_fine'] = 'Segure [E] para reaparecer por $%s',
  ['respawn_bleedout_fine_msg'] = 'Você pagou $%s para reaparecer.',
  ['distress_send'] = 'Pressione [G] para enviar sinal de socorro',
  ['distress_sent'] = 'O sinal de socorro foi enviado para as unidades disponíveis!',
  -- Revive
  ['revive_help'] = 'reviver um jogador',
  -- Item
  ['used_medikit'] = 'Você usou 1 kit médico',
  ['used_bandage'] = 'Você usou 1 curativo',
  ['not_enough_medikit'] = 'Você não tem kit médico.',
  ['not_enough_bandage'] = 'Você não tem curativo.',
  ['healed'] = 'Você foi tratado.',
  -- Blips
  ['blip_hospital'] = 'Hospital',
  ['blip_dead'] = 'Jogador morrendo',
}
