Locales["br"] = {
  -- Inventory
  ["inventory"] = "Inventario ( Peso %s / %s )",
  ["use"] = "Usar",
  ["give"] = "Enviar",
  ["remove"] = "Derrubar",
  ["return"] = "Voltar",
  ["give_to"] = "Enviar Para",
  ["amount"] = "Quantidade",
  ["giveammo"] = "Dar Munição",
  ["amountammo"] = "Quantidade de Munição",
  ["noammo"] = "Insuficiente!",
  ["gave_item"] = "Enviando %sx %s Para %s",
  ["received_item"] = "Recebeu %sx %s De %s",
  ["gave_weapon"] = "Enviando %s Para %s",
  ["gave_weapon_ammo"] = "Enviando ~o~%sx %s para %s para %s",
  ["gave_weapon_withammo"] = "Enviando %s com ~o~%sx %s para %s",
  ["gave_weapon_hasalready"] = "%s ja tem um %s",
  ["gave_weapon_noweapon"] = "%s não tem essa arma",
  ["received_weapon"] = "Recebeu %s De %s",
  ["received_weapon_ammo"] = "Recebeu ~o~%sx %s para seu %s de %s",
  ["received_weapon_withammo"] = "Recebeu %s com ~o~%sx %s de %s",
  ["received_weapon_hasalready"] = "%s tentou lhe dar um %s, mas você já esta arma",
  ["received_weapon_noweapon"] = "%s tentou lhe dar munição para %s, mas você não tem essa arma",
  ["gave_account_money"] = "Enviando $%s (%s) para %s",
  ["received_account_money"] = "Recebeu $%s (%s) de %s",
  ["amount_invalid"] = "Quantidade Invalida",
  ["players_nearby"] = "Nenhum jogador próximo",
  ["ex_inv_lim"] = "Não é possível executar a ação, excedendo o peso máximo de %s",
  ["imp_invalid_quantity"] = "Não é possível executar a ação, a quantidade é inválida",
  ["imp_invalid_amount"] = "Não é possível realizar a ação, o valor é inválido",
  ["threw_standard"] = "Derrubando %sx %s",
  ["threw_account"] = "Derrubando $%s %s",
  ["threw_weapon"] = "Derrubando %s",
  ["threw_weapon_ammo"] = "Derrubando %s com ~o~%sx %s",
  ["threw_weapon_already"] = "Você já tem essa arma",
  ["threw_cannot_pickup"] = "O estoque está cheio, não é possível pegar!",
  ["threw_pickup_prompt"] = "Aperte E para pegar",

  -- Key mapping
  ["keymap_showinventory"] = "Mostrar Inventario",

  -- Salary related
  ["received_salary"] = "Você foi pago: $%s",
  ["received_help"] = "Você recebeu seu cheque de previdência: $%s",
  ["company_nomoney"] = "a empresa em que você trabalha é muito pobre para pagar seu salário",
  ["received_paycheck"] = "salário recebido",
  ["bank"] = "Maze Bank",
  ["account_bank"] = "Banco",
  ["account_black_money"] = "Dinheiro Sujo",
  ["account_money"] = "Cash",

  ["act_imp"] = "Não é possível executar a ação",
  ["in_vehicle"] = "Não é possível realizar a ação, o jogador está em um veículo",
  ["not_in_vehicle"] = "Não é possível realizar a ação, o jogador não está em um veículo",

  -- Commands
  ['command_bring'] = 'Traga o jogador até você',
  ['command_car'] = 'Gerar um veículo',
  ['command_car_car'] = 'Modelo do veículo ou hash',
  ['command_cardel'] = 'Remover veículos nas proximidades',
  ['command_cardel_radius'] = 'Remove todos os veículos dentro do raio especificado',
  ['command_repair'] = 'Repare seu veículo',
  ['command_repair_success'] = 'Veículo reparado com sucesso',
  ['command_repair_success_target'] = 'Um administrador reparou seu veículo',
  ['command_clear'] = 'Limpar texto do bate-papo',
  ['command_clearall'] = 'Limpar texto do bate-papo para todos os jogadores',
  ['command_clearinventory'] = 'Remova todos os itens do inventário de jogadores',
  ['command_clearloadout'] = 'Remova todas as armas do equipamento dos jogadores',
  ['command_freeze'] = 'Congelar um jogador',
  ['command_unfreeze'] = 'Descongelar um jogador',
  ['command_giveaccountmoney'] = 'Dê dinheiro para uma conta específica',
  ['command_giveaccountmoney_account'] = 'Conta para adicionar',
  ['command_giveaccountmoney_amount'] = 'Quantidade a adicionar',
  ['command_giveaccountmoney_invalid'] = 'Nome da conta inválido',
  ['command_removeaccountmoney'] = 'Remover dinheiro de uma conta específica',
  ['command_removeaccountmoney_account'] = 'Conta para remover',
  ['command_removeaccountmoney_amount'] = 'Quantidade a remover',
  ['command_removeaccountmoney_invalid'] = 'Nome da conta inválido',
  ['command_giveitem'] = 'Dê um item ao jogador',
  ['command_giveitem_item'] = 'Nome do Item',
  ['command_giveitem_count'] = 'Quantidade',
  ['command_giveweapon'] = 'Dê uma arma ao jogador',
  ['command_giveweapon_weapon'] = 'Nome da arma',
  ['command_giveweapon_ammo'] = 'Quantidade de munição',
  ['command_giveweapon_hasalready'] = 'O jogador já possui esta arma',
  ['command_giveweaponcomponent'] = 'Dê componente de arma ao jogador',
  ['command_giveweaponcomponent_component'] = 'Nome do componente',
  ['command_giveweaponcomponent_invalid'] = 'Componente de arma inválido',
  ['command_giveweaponcomponent_hasalready'] = 'O jogador já possui este componente de arma',
  ['command_giveweaponcomponent_missingweapon'] = 'O jogador não possui esta arma',
  ['command_goto'] = 'Teleporte-se para um jogador',
  ['command_kill'] = 'Mate um jogador',
  ['command_save'] = 'Forçar o salvamento dos dados de um jogador',
  ['command_saveall'] = 'Forçe a salvar todos os jogadores',
  ['command_setaccountmoney'] = 'Defina o dinheiro em uma conta específica',
  ['command_setaccountmoney_amount'] = 'Quantidade',
  ['command_setcoords'] = 'Teleporte para coordenadas especificadas',
  ['command_setcoords_x'] = 'X valor',
  ['command_setcoords_y'] = 'Y valor',
  ['command_setcoords_z'] = 'Z valor',
  ['command_setjob'] = 'Defina o trabalho de um jogador',
  ['command_setjob_job'] = 'Nome',
  ['command_setjob_grade'] = 'Nivel do trabalho',
  ['command_setjob_invalid'] = 'o trabalho, o nivel ou ambos são inválidos',
  ['command_setgroup'] = 'Defina um grupo de permissão de jogadores',
  ['command_setgroup_group'] = 'Nome do Grupo',
  ['commanderror_argumentmismatch'] = 'Contagem de argumentos inválidos (passado %s, desejada %s)',
  ['commanderror_argumentmismatch_number'] = 'Argumento inválido #%s tipo de dados (passado string, desejada number)',
  ['commanderror_argumentmismatch_string'] = 'Argumento inválido #%s tipo de dados (passado number, desejada string)',
  ['commanderror_invaliditem'] = 'Item inválido',
  ['commanderror_invalidweapon'] = 'Arma inválida',
  ['commanderror_console'] = 'Comando não pode ser executado no console',
  ['commanderror_invalidcommand'] = 'Comando inválido - /%s',
  ['commanderror_invalidplayerid'] = 'O jogador especificado não está online',
  ['commandgeneric_playerid'] = 'ID do servidor do jogador',
  ['command_giveammo_noweapon_found'] = '%s não tem essa arma',
  ['command_giveammo_weapon'] = 'Nome da arma',
  ['command_giveammo_ammo'] = 'Quantidade de munição',
  ['tpm_nowaypoint'] = 'Nenhum ponto de referência definido.',
  ['tpm_success'] = 'Teletransportado com sucesso',

  ['noclip_message'] = 'Noclip esta %s',
  ['enabled'] = '~g~Habilitado~s~',
  ['disabled'] = '~r~Deshabilitado~s~',

  -- Locale settings
  ["locale_digit_grouping_symbol"] = ",",
  ["locale_currency"] = "£%s",

  -- Weapons

  -- Melee
  ["weapon_dagger"] = "Adaga",
  ["weapon_bat"] = "Taco de Baseball",
  ["weapon_battleaxe"] = "Machado de Batalha",
  ["weapon_bottle"] = "Garrafa",
  ["weapon_crowbar"] = "Pé de cabra",
  ["weapon_flashlight"] = "Lanterna",
  ["weapon_golfclub"] = "Taco de Golf",
  ["weapon_hammer"] = "Martelo",
  ["weapon_hatchet"] = "Machadinha",
  ["weapon_knife"] = "Faca",
  ["weapon_knuckle"] = "Soco ingles",
  ["weapon_machete"] = "Machete",
  ["weapon_nightstick"] = "Bastão",
  ["weapon_wrench"] = "Chave de Grifo",
  ["weapon_poolcue"] = "Taco de Sinuca",
  ["weapon_stone_hatchet"] = "Machadinha de pedra",
  ["weapon_switchblade"] = "Canivete",

  -- Handguns
  ["weapon_appistol"] = "Pistola AP",
  ["weapon_ceramicpistol"] = "Pistola Cerâmica",
  ["weapon_combatpistol"] = "Pistola de Combate",
  ["weapon_doubleaction"] = "Revólver de dupla ação",
  ["weapon_navyrevolver"] = "Revólver da Marinha",
  ["weapon_flaregun"] = "Sinalizador",
  ["weapon_gadgetpistol"] = "Pistola de Perico",
  ["weapon_heavypistol"] = "Pistola Pesada",
  ["weapon_revolver"] = "Revólver Pesado",
  ["weapon_revolver_mk2"] = "Revólver Pesado MK2",
  ["weapon_marksmanpistol"] = "Pistola de atirador",
  ["weapon_pistol"] = "Pistola",
  ["weapon_pistol_mk2"] = "Pistola MK2",
  ["weapon_pistol50"] = "Pistola .50",
  ["weapon_snspistol"] = "SNS Pistola",
  ["weapon_snspistol_mk2"] = "SNS Pistola MK2",
  ["weapon_stungun"] = "Taser",
  ["weapon_raypistol"] = "Up-N-Atomizer",
  ["weapon_vintagepistol"] = "Pistola Vintage",

  -- Shotguns
  ["weapon_assaultshotgun"] = "Escopeta de assalto",
  ["weapon_autoshotgun"] = "Escopeta automática",
  ["weapon_bullpupshotgun"] = "Escopeta Bullpup",
  ["weapon_combatshotgun"] = "Escopeta de Combate",
  ["weapon_dbshotgun"] = "Escopeta de cano duplo",
  ["weapon_heavyshotgun"] = "Escopeta Pesada",
  ["weapon_musket"] = "Mosquete",
  ["weapon_pumpshotgun"] = "Escopeta",
  ["weapon_pumpshotgun_mk2"] = "Escopeta MK2",
  ["weapon_sawnoffshotgun"] = "Escopeta serrada",

  -- SMG & LMG
  ["weapon_assaultsmg"] = "SMG Assalto",
  ["weapon_combatmg"] = "MG Combate",
  ["weapon_combatmg_mk2"] = "MG Combate MK2",
  ["weapon_combatpdw"] = "PDW Combat",
  ["weapon_gusenberg"] = "Varredor Gusenberg",
  ["weapon_machinepistol"] = "Pistola Metralhadora",
  ["weapon_mg"] = "MG",
  ["weapon_microsmg"] = "Micro SMG",
  ["weapon_minismg"] = "Mini SMG",
  ["weapon_smg"] = "SMG",
  ["weapon_smg_mk2"] = "SMG MK2",
  ["weapon_raycarbine"] = "Infernal Profano",

  -- Rifles
  ["weapon_advancedrifle"] = "Rifle Avançado",
  ["weapon_assaultrifle"] = "Fuzil de assalto",
  ["weapon_assaultrifle_mk2"] = "Fuzil de Assalto MK2",
  ["weapon_bullpuprifle"] = "Rifle Bullpup",
  ["weapon_bullpuprifle_mk2"] = "Rifle Bullpup MK2",
  ["weapon_carbinerifle"] = "Carabina",
  ["weapon_carbinerifle_mk2"] = "Carabina MK2",
  ["weapon_compactrifle"] = "Rifle Compacto",
  ["weapon_militaryrifle"] = "Rifle Militar",
  ["weapon_specialcarbine"] = "Carabina Especial",
  ["weapon_specialcarbine_mk2"] = "Carabina Especial MK2",
  ["weapon_heavyrifle"] = "Rifle Pesado",

  -- Sniper
  ["weapon_heavysniper"] = "Sniper Pesada",
  ["weapon_heavysniper_mk2"] = "Sniper Pesada MK2",
  ["weapon_marksmanrifle"] = "Rifle de atirador",
  ["weapon_marksmanrifle_mk2"] = "Rifle de atirador MK2",
  ["weapon_sniperrifle"] = "Sniper Rifle",

  -- Heavy / Launchers
  ["weapon_compactlauncher"] = "Lançador compacto",
  ["weapon_firework"] = "Lançador de fogos de artifício",
  ["weapon_grenadelauncher"] = "Lançador de granada",
  ["weapon_hominglauncher"] = "Lançador Teleguiado",
  ["weapon_minigun"] = "Minigun",
  ["weapon_railgun"] = "Railgun",
  ["weapon_rpg"] = "Lança Foguetes",
  ["weapon_rayminigun"] = "Widowmaker",

  -- Criminal Enterprises DLC
  ["weapon_metaldetector"] = "Detector de metal",
  ["weapon_precisionrifle"] = "Rifle de Precisão",
  ["weapon_tactilerifle"] = "Carabina de serviço",

  -- Drug wars dlc
  ["weapon_candycane"] = "Candycane",
  ["weapon_acidpackage"] = "Pacote ácido",
  ["weapon_pistolxm3"] = "Pistol8 x3m",
  ["weapon_railgunxm3"] = "Railgun",

  -- Thrown
  ["weapon_ball"] = "Baseball",
  ["weapon_bzgas"] = "BZ Gas",
  ["weapon_flare"] = "Flare",
  ["weapon_grenade"] = "Grenada",
  ["weapon_petrolcan"] = "Galão",
  ["weapon_hazardcan"] = "Galão Perigoso",
  ["weapon_molotov"] = "Coquetel Molotov",
  ["weapon_proxmine"] = "Mina de Proximidade",
  ["weapon_pipebomb"] = "Bomba caseira",
  ["weapon_snowball"] = "Bola de neve",
  ["weapon_stickybomb"] = "Bomba pegajosa",
  ["weapon_smokegrenade"] = "Gás lacrimogêneo",

  -- Special
  ["weapon_fireextinguisher"] = "Extintor de incêndio",
  ["weapon_digiscanner"] = "Scanner digital",
  ["weapon_garbagebag"] = "Saco de lixo",
  ["weapon_handcuffs"] = "Algemas",
  ["gadget_nightvision"] = "Visão noturna",
  ["gadget_parachute"] = "pára-quedas",

  -- Weapon Components
  ["component_knuckle_base"] = "Modelo básico",
  ["component_knuckle_pimp"] = "o cafetão",
  ["component_knuckle_ballas"] = "os Ballas",
  ["component_knuckle_dollar"] = "o traficante",
  ["component_knuckle_diamond"] = "a rocha",
  ["component_knuckle_hate"] = "o odiador",
  ["component_knuckle_love"] = "o amante",
  ["component_knuckle_player"] = "o jogador",
  ["component_knuckle_king"] = "o rei",
  ["component_knuckle_vagos"] = "os Vagos",

  ["component_luxary_finish"] = "Acabamento de arma luxuoso",

  ["component_handle_default"] = "Punho padrão",
  ["component_handle_vip"] = "Punho VIP",
  ["component_handle_bodyguard"] = "Punho escolta",

  ["component_vip_finish"] = "Concluir vip",
  ["component_bodyguard_finish"] = "Concluir escolta",

  ["component_camo_finish"] = "Camuflagem digital",
  ["component_camo_finish2"] = "Camuflagem pincelada",
  ["component_camo_finish3"] = "Camuflagem floresta",
  ["component_camo_finish4"] = "Camuflagem caveira",
  ["component_camo_finish5"] = "Camuflagem sessanta Nove",
  ["component_camo_finish6"] = "Camuflagem perseus",
  ["component_camo_finish7"] = "Camuflagem leopardo",
  ["component_camo_finish8"] = "Camuflagem zebra",
  ["component_camo_finish9"] = "Camuflagem geometrica",
  ["component_camo_finish10"] = "Camuflagem boom",
  ["component_camo_finish11"] = "Camuflagem patriota",
 
  ["component_camo_slide_finish"] = "Camuflagem slide digital",
  ["component_camo_slide_finish2"] = "Camuflagem Slide pincelada",
  ["component_camo_slide_finish3"] = "Camuflagem Slide Floresta",
  ["component_camo_slide_finish4"] = "Camuflagem Slide Caveira",
  ["component_camo_slide_finish5"] = "Camuflagem Slide sessanta Nove",
  ["component_camo_slide_finish6"] = "Camuflagem Slide perseus",
  ["component_camo_slide_finish7"] = "Camuflagem Slide leopard",
  ["component_camo_slide_finish8"] = "Camuflagem Slide zebra",
  ["component_camo_slide_finish9"] = "Camuflagem Slide geometric",
  ["component_camo_slide_finish10"] = "Camuflagem Slide boom",
  ["component_camo_slide_finish11"] = "Camuflagem Slide Patriota",

  ["component_clip_default"] = "Carregador Padrao",
  ["component_clip_extended"] = "Carregador extendido",
  ["component_clip_drum"] = "Carregador tambor",
  ["component_clip_box"] = "Carregador Caixa",

  ["component_scope_holo"] = "Mira Holografica",
  ["component_scope_small"] = "Mira Pequena",
  ["component_scope_medium"] = "Mira Media",
  ["component_scope_large"] = "Mira Grande",
  ["component_scope"] = "Mira montada",
  ["component_scope_advanced"] = "Mira avançada",
  ["component_ironsights"] = "mira de ferro",

  ["component_suppressor"] = "Silenciador",
  ["component_compensator"] = "Compensador",

  ["component_muzzle_flat"] = "Freio de boca plano",
  ["component_muzzle_tactical"] = "Freio de boca tactico",
  ["component_muzzle_fat"] = "Freio de boca com ponta gorda",
  ["component_muzzle_precision"] = "freio de boca de precisão",
  ["component_muzzle_heavy"] = "freio de boca resistente",
  ["component_muzzle_slanted"] = "freio de boca inclinado",
  ["component_muzzle_split"] = "Freio de boca com ponta dividida",
  ["component_muzzle_squared"] = "Freio de boca quadrado",

  ["component_flashlight"] = "Lanterna",
  ["component_grip"] = "Punho",

  ["component_barrel_default"] = "Cano Padrao",
  ["component_barrel_heavy"] = "Cano Longo",

  ["component_ammo_tracer"] = "Munição traçante",
  ["component_ammo_incendiary"] = "munição incendiária",
  ["component_ammo_hollowpoint"] = "munição de ponta oca",
  ["component_ammo_fmj"] = "Munição fMJ",
  ["component_ammo_armor"] = "munição perfurante de armadura",
  ["component_ammo_explosive"] = "Munição incendiária perfurante de armadura",

  ["component_shells_default"] = "Capsula padrão",
  ["component_shells_incendiary"] = "Capsulas respiração de dragão",
  ["component_shells_armor"] = "Capsulas chumbo grosso",
  ["component_shells_hollowpoint"] = "Capsulas flechette",
  ["component_shells_explosive"] = "Capsula explosiva",

  -- Weapon Ammo
  ["ammo_rounds"] = "round(s)",
  ["ammo_shells"] = "Capsula(s)",
  ["ammo_charge"] = "Carregar",
  ["ammo_petrol"] = "Galoes de combustivel",
  ["ammo_firework"] = "Fogo de Artificio(s)",
  ["ammo_rockets"] = "Foguete(s)",
  ["ammo_grenadelauncher"] = "Granada(s)",
  ["ammo_grenade"] = "Grenada(s)",
  ["ammo_stickybomb"] = "Bomba(s)",
  ["ammo_pipebomb"] = "Bomba(s)",
  ["ammo_smokebomb"] = "Bomba(s)",
  ["ammo_molotov"] = "coquetel(s)",
  ["ammo_proxmine"] = "mina(s)",
  ["ammo_bzgas"] = "Garrafa(s)",
  ["ammo_ball"] = "Bola(s)",
  ["ammo_snowball"] = "bola de neve(s)",
  ["ammo_flare"] = "Sinalizador(s)",
  ["ammo_flaregun"] = "Sinalizador(s)",

  -- Weapon Tints
  ["tint_default"] = "Skin Padrao",
  ["tint_green"] = "Skin Verde",
  ["tint_gold"] = "Skin Gold",
  ["tint_pink"] = "Skin Rosa",
  ["tint_army"] = "Skin Militar",
  ["tint_lspd"] = "Skin Azul",
  ["tint_orange"] = "Skin Alaranjada",
  ["tint_platinum"] = "Skin Platina",
}
